language: csharp
sudo: required
dist: trusty
mono:
  - latest
dotnet: 3.1.100
os:
  - linux
script:
  - ./build.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always
